#hola
services:
  proxy:
    build: ./proxy
    networks:
      - frontend

  nginx: #wordpress?
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
    context: requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443" 		# on indique le port qui sera exposé a la machine locale
    restart: on-failure

  mariadb:
    container_name: mariadb	
    networks:
    - inception 
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
      env_file: .env 
    volumes:
      - mariadb:/var/lib/mysql
      restart: unless-stopped 
    expose:
      - "3306"

networks:
  frontend:
    # Use a custom driver
    driver: custom-driver-1
  backend:
    # Use a custom driver which takes special options
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"