# # #hola
# services:
#   mariadb:
#     container_name: mariadb
#     build:          ./requirements/mariadb/
#     image:          mariadb:inception
#     env_file:       .env
#     networks:
#         - inception
#     restart:        on-failure
#     volumes:
#         - mariadb:/var/lib/mysql/

#   wordpress:
#     container_name: wordpress
#     build:
#       context: ./requirements/wordpress/
#       dockerfile: Dockerfile
#     image:          wordpress:inception
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/wordpress/
#     networks:
#       - inception
#     depends_on:
#       - mariadb
#     restart: on-failure
#     expose:
#       - "9000"

#   nginx:
#     container_name: nginx
#     volumes:
#       - wordpress:/var/www/wordpress/
#     networks:
#       - inception
#     build:
#       context: ./requirements/nginx/
#       dockerfile: Dockerfile
#     image:          nginx:inception
#     env_file: .env
#     depends_on:
#       - wordpress
#     ports:
#       - "443:443"
#     restart: on-failure

# # networks:
# #   frontend:
# #     driver: custom-driver-1
# #   backend:
# #     driver: custom-driver-2
# #     driver_opts:
# #       foo: "1"
# #       bar: "2"

# networks:
#   inception:
#     name:   inception
#     driver: bridge

# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: 'Users/diegofranciscolunalopez/Documents/data/wordpress'
#       # device: '/home/dluna-lo/data/wordpress'
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: 'Users/diegofranciscolunalopez/Documents/data/mariadb'
#       # device: '/home/dluna-lo/data/mariadb'


################################################################################################
version: "3.7"

services:
    nginx:
        container_name: nginx
        build:          ./requirements/nginx/
        image:          nginx:inception
        env_file:       .env
        networks:
            - inception
        ports:
            - "443:443"
        restart:        on-failure
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - wordpress
    mariadb:
        container_name: mariadb
        build:          ./requirements/mariadb/
        image:          mariadb:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:
            - mariadb-data:/var/lib/mysql/
    wordpress:
        container_name: wordpress
        build:          ./requirements/wordpress/
        image:          wordpress:inception
        env_file:       .env
        networks:
            - inception
        restart:        on-failure
        volumes:
            - wordpress-data:/var/www/html/
        depends_on:
            - mariadb

networks:
    inception:
        name:   inception
        driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: Users/diegofranciscolunalopez/Documents/data/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: Users/diegofranciscolunalopez/Documents/data/wordpress-data