#hola
services:
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build:
    context: requirements/wordpress
    dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose:
    - "9000"

  nginx: #wordpress?
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
    context: requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    depends_on:
    - wordpress
    ports:
    - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    networks:
    - inception 
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
      env_file: .env 
    volumes:
      - mariadb:/var/lib/mysql
      restart: unless-stopped 
    expose:
      - "3306"

# networks:
#   frontend:
#     driver: custom-driver-1
#   backend:
#     driver: custom-driver-2
#     driver_opts:
#       foo: "1"
#       bar: "2"

networks:
  inception:
  driver: bridge

volumes:
  wordpress:
    driver: local 
    driver_opts:
    type: 'none' 									
    o: 'bind'
    device: '/Users/login/data/wordpress' 		
  mariadb:
    driver: local
    driver_opts:
    type: 'none'
    o: 'bind'										 
    device: '/Users/login/data/mariadb'			